name: Unpub
concurrency: release-${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy as'
        type: environment

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      PKG_NAME: 'Connect Kit'
      PKG_DIR: 'packages/connect-kit'
      PKG_SPEC: '@ledgerhq/connect-kit'
      # use 'latest' for release, 'alpha' or 'beta' for pre-releases
      PKG_RELEASE_TAG: 'latest'
      # make sure it matches the version on package.json
      PKG_VERSION: '1.1.8'
      GIT_TAG_PREFIX: 'ck-'
    steps:
      - name: Publish
        run: |
          cd ${{ env.PKG_DIR }}
          npm unpublish @ledgerhq/connect-kit@1.1.5
          npm unpublish @ledgerhq/connect-kit@1.1.6
          npm unpublish @ledgerhq/connect-kit@1.1.7
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
